Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,10 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
-
 name: Java CI with Gradle
 
 on:
@@ -12,93 +5,66 @@ on:
     branches: [ "master" ]
 
 jobs:
-  build:
-
+  build-and-push-docker-image:
     runs-on: ubuntu-latest
     permissions:
       contents: read
-      
-    # 1. Java 17 세팅
+
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
+      
+    # Java 17 setup
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'
 
-    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
-    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
+    # Configure and setup Gradle
     - name: Setup Gradle
-      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
-    
-    # 2. Spring Boot 애플리케이션 빌드
+      uses: gradle/actions/setup-gradle@v3.1.0
+      
+    # Build Spring Boot application
     - name: Build with Gradle Wrapper
       run: ./gradlew build
-
-    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
-    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
-    #
-    # - name: Setup Gradle
-    #   uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
-    #   with:
-    #     gradle-version: '8.5'
-    #
-    # - name: Build with Gradle 8.5
-    #   run: gradle build
-
-  dependency-submission:
-
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up JDK 17
-      uses: actions/setup-java@v4
-      with:
-        java-version: '17'
-        distribution: 'temurin'
-
-    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
-    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
+      
+    # Submit dependency graph for Dependabot
     - name: Generate and submit dependency graph
-      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
-    
-    # 3. Docker 이미지 빌드
-    - name: docker image build
+      uses: gradle/actions/dependency-submission@v3.1.0
+
+    # Docker image build
+    - name: Build Docker image
       run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday .
 
-    # 4. DockerHub 로그인
-    - name: docker login
+    # DockerHub login
+    - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-    # 5. Docker Hub 이미지 푸시
-    - name: docker Hub push
+    # Push Docker image to Docker Hub
+    - name: Push Docker image to Docker Hub
       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday
 
-  # 위 과정에서 푸시한 이미지를 ec2에서 풀받아서 실행시키는 과정
   run-docker-image-on-ec2:
-    needs: build-docker-image
-    runs-on: self-hosted
-
-  steps:
-      # 최신 이미지를 풀받습니다
-      - name: docker pull
+    needs: build-and-push-docker-image
+    runs-on: [self-hosted]
+    steps:
+      # Pull the latest image
+      - name: Pull latest Docker image
         run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday
 
-      # 기존의 컨테이너를 중지시킵니다
-      - name: docker stop container
-        run: sudo docker stop $(sudo docker ps -q) 2>/dev/null || true
+      # Stop existing container
+      - name: Stop existing Docker container
+        run: sudo docker stop $(sudo docker ps -q) || true
 
-      # 최신 이미지를 컨테이너화하여 실행시킵니다
-      - name: docker run new container
-        run: sudo docker run --name github-actions-demo --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday
+      # Run new container
+      - name: Run new Docker container
+        run: sudo docker run --name ggamanggarden-parentsday --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/ggamanggarden-parentsday
 
-      # 미사용 이미지를 정리합니다
-      - name: delete old docker image
-        run: sudo docker system prune -f
+      # Cleanup unused Docker images
+      - name: Clean up old Docker images
+        run: sudo docker system prune -a -f
+
